---

- name: install consul
  copy: src=consul dest=/usr/bin/consul mode=0755

- name: copy upstart file
  copy: src=consul.conf dest=/etc/init/consul.conf mode=0644

- name: create /etc/consul.d
  file: path=/etc/consul.d state=directory mode=0755
