---

- name: restart consul
  service: >
    name=consul
    state=restarted

- name: reload consul
  service: >
    name=consul
    state=reloaded

- name: clean consul data
  file: >
    path=/var/lib/consul/*
    state=absent

- name: restart dnsmasq
  service: >
    name=dnsmasq
    state=restarted
